### ISSUE TITLE
NATS package updates for Swan Lake alpha4

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#1175]
**Tasks:**

- [x] Client init change
- [x] Listener init change
- [x] Examples update with latest changes 
- [x] Package.md update with latest changes
- [x] Remove onMessage from service definition in the package
- [x] Change `duration` in `requestMessage()` to `decimal`
