### ISSUE TITLE
STAN package updates for Swan Lake alpha4

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#1176]
**Tasks:**

- [x] Client init change
- [x] Listener init change
- [x] Examples update with latest changes 
- [x] Package.md update with latest changes
