### ISSUE TITLE
Kafka package updates for Swan Lake alpha4

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#1177]
**Tasks:**

- [x] Consumer init change
- [x] Producer init change
- [x] Examples update with latest changes 
- [x] Package.md update with latest changes
- [x] Remove onConnnsumerRecord from service definition in the package
- [x] [SecureSocket change](https://github.com/ballerina-platform/ballerina-standard-library/issues/1170)
