### ISSUE TITLE
GraphQL compiler plugin improvements 

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#1338]
**Description:**

- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/1339 Input types should be valid for the union of [any valid type or nil]
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/1344 Returning a union of distinct service types should be valid
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/1348 The returning service type should be validated as a GraphQL service
