### ISSUE TITLE
Improve API documentation for WebSub Module

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1340]
### Description: ###
Improve the API documentation in `websub module`.

#### Task Breakdown ####
- [X] Update `package.md` document.
- [X] Update `module.md` document.
- [X] Update Ballerina API documentation for `websub` APIs
- [X] Fix `websub` test cases according to Ballerina Anti-Patterns guide
