### ISSUE TITLE
Improve API documentation for WebSubHub Module

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1341]
### Description: ###
Improve the API documentation in `websubhub module`.

#### Task Breakdown ####
- [X] Update `package.md` document.
- [X] Update `module.md` document.
- [X] Update Ballerina API documentation for `websubhub` APIs
- [X] Fix `websubhub` test cases according to Ballerina Anti-Patterns guide
