### ISSUE TITLE
Refactor WebSubHub module codebase

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1485]
**Description:**
Refactor `websubhub module` codebase but without changing any logic.

**Task Breakdown**
- [ ] Topic Registration/Deregistration Flow
- [ ] Subscription/Unsubscription Flow
- [ ] Contend Distribution Flow
- [ ] HubClient
- [ ] PublisherClient
