### ISSUE TITLE
Refactor WebSubHub module codebase

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#1486]
**Description:**
Refactor `websubhub module` codebase but without changing any logic.

**Task Breakdown**
- [X] Topic Registration/Deregistration Flow
- [X] Subscription/Unsubscription Flow
- [x] Contend Distribution Flow
- [x] HubClient
- [x] PublisherClient

Related to #2164
