### ISSUE TITLE
Add a File content listener to the FTP module

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#1490]
**Description:**
Existing FTP listener only provides watch events of added and deleted file links. File content listener can be introduced to read the content of a file once it is added to the remote file system.

**Comment by niveathika** [comment]
The PC issue https://github.com/wso2-enterprise/integration-product-management/issues/481

**Comment by SachinAkash01** [comment]
Added the proposal PR: https://github.com/ballerina-platform/ballerina-spec/pull/1388

**Comment by SachinAkash01** [comment]
### Task List: Implementation of the FTP Content Listener

- [x] **Phase 1: Compiler Plugin Validation**
    - [x] Update Service Validator.
    - [x] Create New Function Validator.
    - [x] Update Code Templates.
- [x] **Phase 2: Ballerina API Layer**
    - [x] Update Service Type Definition.
- [x] **Phase 3: Native Java Implementation**
    - [x] Extend FtpUtil.
    - [x] Modify FtpListener.
    - [x] Add Content Fetching Support.
 - [x] **Phase 4: Testing**
    - [x] Integration Tests.
    - [x] Update Test Utils.
- [ ] **Phase 5: Documentation**

> ETA:
> - Best case: 07/10/2025
> - Average case: 08/10/2025
> - Worst case: 10/10/2025

**Comment by SachinAkash01** [comment]
The implementation of the File Content Listener feature has taken longer than initially anticipated due to the key enhancements and refinements made beyond the initial proposal.

#### Initial Design

The original proposal focused on introducing content-first callbacks (`onFile`, `onFileText`, `onFileJson`, `onFileXml`, `onFileCsv`) to eliminate boilerplate code for fetching file content. This core functionality has been implemented and validated.

#### Enhanced Dispatching Logic (New Addition)

After the initial implementation, we identified that users would benefit from automatic content method routing based on file extensions when multiple patterns are configured. This led to Default Extension-to-Method Mapping: Automatic routing of files to appropriate content methods:

- `.json` → `onFileJson`
- `.xml` → `onFileXml`
- `.csv` → `onFileCsv`
- `.txt` → `onFileText`
- Other extensions → `onFile` (generic handler)

#### Annotation Based Override Mechanism (New Addition)

To provide flexibility beyond default mappings, we introduced the `@ftp:FileConfig `annotation:

```balllerina
@ftp:FileConfig { pattern: ".*\\.txt$" }
remote function onFileJson(json content, ftp:FileInfo fileInfo) returns error? {
    // Process .txt files as JSON
}
```

This enables users to override default behavior when file extensions don't match content format (e.g., JSON data in .txt files).

#### Graceful Fallback Behaviour (New Addition)

Implemented a three-tier fallback chain to handle scenarios where specific content methods aren't available:

1. Primary Fallback: `onFile(stream<byte[], error> ...)` - Generic byte stream handling
2. Tertiary: Compilation error if no methods are implemented

The draft [PR](https://github.com/ballerina-platform/module-ballerina-ftp/pull/1499) with the initial implementation has been already sent. Currently I have implemented all the new additions and now working on the test cases and the documentation.  Planning to finish this task by today EOD (17/10/2025).
