### ISSUE TITLE
Tooling support for SQL connectors

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#2058]
**Description:**
Add Tooling support for SQL connectors,

Following tooling support must be implemented,
- [ ] Diagnostics
- [ ] Code completions
- [ ] Code actions
- [ ] Formatting
- [ ] Hover

**Comment by niveathika** [comment]
Diagnostics

- [ ] Improve 'cannot infer type for parameter 'rowType' error for query(). This needs to include to add eithrt `rowType` param or not ignore the return
- [ ] Improve 'cannot infer type for parameter 'rowType' error for queryRow(). Here we need to validate that this of any data type. As of now, the compiler allows stream.
- [ ] Each `OutParameter` get method to validate typedescription param at compile time.


Code Completions

- [ ] Add completion for parameterised query param. (TBD with the lang server team to improve this support for all basic raw templates)
- [ ] Sort suggested remote function based on LHS type. (Bug)

Code Action
- [ ] OutParmeter suggests a supported type description based on the object type.

Hover

- [ ] Hover for function completion to include parameter description and default values if any
- [ ] Connect documentation for parameterized query
- [ ] Hover missing some information such as function names and stream completion type (Bug)

**Comment by niveathika** [comment]
The updated tooling actions are based on 1.1.0 changes,

Diagnostics

- [ ] Improve inferring error for query(). 
        Current: cannot infer type for parameter 'rowType'(BCE3934`)
        Hint: Parameter 'rowType' should be explicitly defined when the return data is ignored. 
- [ ] Improve inferring error for queryRow(). 
        Current: incompatible type for parameter 'returnType' with inferred typedesc value: expected 'typedesc<anydata>', found 'typedesc'(BCE3931)
        Hint: Parameter 'returnType' should be explicitly defined when the return data is ignored.
- [ ] Improve inferring error for OutParameter.
        Current: incompatible type for parameter 'returnType' with inferred typedesc value: expected 'typedesc<anydata>', found 'typedesc'(BCE3931)
        Hint: Parameter 'typeDesc' should be explicitly defined when the return data is ignored.
- [ ] Each `OutParameter` get method to validate type description param at compile time.
        - Validate for explicity defined param (Done)
        - Validate for inferred typeDesc param
- [ ] Need to validate negative values for connection pool configs.
        - Validate for variable assignments (Done)
        - Validate for inline definitions at SQL connectors 

Code Completions

- [ ] Sort SQL remote function based on LHS (https://github.com/ballerina-platform/ballerina-lang/issues/33672)

Hover

- [ ] Include default values in init method (https://github.com/ballerina-platform/ballerina-lang/issues/33670)
- [ ] Connect documentation for parameterized query (https://github.com/ballerina-platform/ballerina-lang/issues/33673)
- [ ] https://github.com/ballerina-platform/ballerina-lang/issues/33671
- [ ] Remove fields description for sql:PArameterizedQuery (https://github.com/ballerina-platform/ballerina-lang/issues/33669)

**Comment by niveathika** [comment]
Closing this as the remaining tooling support must be enabled from the LS code and those are tracked in seperate issues.
