### ISSUE TITLE
Module Revamp for Ballerina Swan Lake

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#236]
**Description:**
Improving the current module for Ballerina Swan Lake

**Sub Tasks:**
- [x] [Feature Comparison Research](https://github.com/ballerina-platform/module-ballerinax-nats/issues/32)
- [x] [Design for Service Typing](https://github.com/ballerina-platform/module-ballerinax-nats/issues/19)
- [x] [Design revamp for client APIs](https://github.com/ballerina-platform/ballerina-standard-library/issues/578) 
- [x] Service design implementation
- [x] Client design implementation
- [x] Tests
- [x] Examples
