### ISSUE TITLE
Rewrite Regex Parser in Ballerina

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-standard-library#2716]
**Description:**
The ballerina Regex package has APIs for searching and manipulating strings by using Java APIs internally. If we implement a regex engine, we can remove java usage from this module. 

These are the part of this task.
- [ ] Create the proposal
- [ ] Get feedback from others and finalize the design
- [ ] Implementation
    - [ ] Regex validation https://github.com/ballerina-platform/ballerina-standard-library/issues/2718
    - [ ] Implement algorithm https://github.com/ballerina-platform/ballerina-standard-library/issues/2726
    - [ ] Update split API https://github.com/ballerina-platform/ballerina-standard-library/issues/2719
    - [ ] Update matches API https://github.com/ballerina-platform/ballerina-standard-library/issues/2721
    - [ ] Update replaceFirst API https://github.com/ballerina-platform/ballerina-standard-library/issues/2725
    - [ ] Update replaceAll API https://github.com/ballerina-platform/ballerina-standard-library/issues/2724
    - [ ] Update find API https://github.com/ballerina-platform/ballerina-standard-library/issues/2723
    - [ ] Update findAll API https://github.com/ballerina-platform/ballerina-standard-library/issues/2722

**Comment by kalaiyarasiganeshalingam** [comment]
According to this suggestion https://github.com/ballerina-platform/ballerina-standard-library/issues/2689#issuecomment-1050657949, we have deprioritized this task now. Hence closing this issue.
