### ISSUE TITLE
Rewrite Ballerina UUID module in Ballerina

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#2730]
**Description:**
This task is to rewrite the Ballerina UUID module in Ballerina and remove all native code and dependencies. We will break this 

- [x]  Re-implement Version generation logic in Ballerina(#2728)
- [x]  Re-implement Utility functions in Ballerina(#2727)
- [x]  Re-implement UUID of Type 1 generation in Ballerina(#2720)
- [x]  Re-implement UUID of Type 3 generation in Ballerina
- [x]  Re-implement UUID of Type 4 generation in Ballerina
- [x]  Re-implement UUID of Type 5 generation in Ballerina

**Comment by MadhukaHarith92** [comment]
Closing since this task is completed.
