### ISSUE TITLE
Write the Generated GraphQL Schema to a File

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-standard-library#3531]
**Description:**
The Ballerina GraphQL package generates the schema for a given Ballerina GraphQL service at the compile time. Currently, the generated schema is exposed to the outside only via introspection. Since the Ballerina GraphQL module uses the code-first approach, users can not have the generated schema from the service in Schema Definition Language(SDL). The only way to check the schema in SDL is by using a client tool (e.g., GraphQL Playground). Therefore need a way to export the schema in SDL.

Subtasks:
- [x] [Update GraphQL commons package with `SdlSchemaStringGenerator`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3570)
- [x] [Expose the GraphQL Commons API to be used in GraphQL CLI Tool](https://github.com/ballerina-platform/ballerina-standard-library/issues/3571)
- [x] [Add schema generating support with CLI command](https://github.com/ballerina-platform/ballerina-standard-library/issues/3532)
- [ ] Add schema generating support with build flag
- [ ] [Update the docs](https://github.com/ballerina-platform/ballerina-standard-library/issues/3737)

**Comment by DimuthuMadushan** [comment]
The proposal: https://github.com/ballerina-platform/ballerina-standard-library/issues/3286
