### ISSUE TITLE
Implement WebSocket service to AsyncAPI generation tool

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-standard-library#4290]
1. **Description:**
This issue covers the main tasks that will be completed in the WebSocket AsyncAPI generation tool.
More information can be found here,

https://docs.google.com/document/d/1xkW_T8slQs201LG2EJyouz3iBxV-0ureVtXCXeANTJw/edit?usp=sharing

Task break down

- [x] Familiarizing Ballerina language
- [x] Familiarizing AsyncAPI
- [x] Propose a design for Ballerina WebSocket code to AsyncAPI conversion
- [x] Initial implementations of the Service to AsyncAPI specification tool
- [x] [Add ChannelTests for Ballerina WebSocket service to AsyncAPI generator cmd tool](https://github.com/ballerina-platform/ballerina-standard-library/issues/4291)
- [x] [Add DataTypeTests for Ballerina WebSocket service to AsyncAPI generator cmd tool](https://github.com/ballerina-platform/ballerina-standard-library/issues/4292)
- [x] [Add ResponseTests for Ballerina WebSocket service to AsyncAPI generator cmd tool](https://github.com/ballerina-platform/ballerina-standard-library/issues/4293)

**Comment by Bhashinee** [comment]
Need to get this fine-tuned to include it as a build tool.

As the initial step, need to do the following tasks,

- [ ] Update the code to match the new APIs from the Ballerina Lang.
- [ ] Update the apicurio version.
- [ ] Update the Ballerina version
- [ ] Update the Gradle scripts
- [ ] Current build is not passing with spotbugs. Have to fix the code.
