### ISSUE TITLE
Fix security vulnerabilities reported with 1.2.x

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#4366]
**Description:**
> $Subject

**Tasks:**

Need to resolve the following vulnerabilities related to `mime`:
- [x] [Insufficient Entropy](https://cwe.mitre.org/data/definitions/331.html) - [code link](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/mime/src/main/java/org/ballerinalang/mime/util/MimeUtil.java#L434)
- [x] [Improper Resource Shutdown or Release](https://cwe.mitre.org/data/definitions/404.html) - [code link](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/mime/src/main/java/org/ballerinalang/mime/util/MultipartDataSource.java#L87)

Need to check the vulnerability fixes related to `http`:
- Improper Output Neutralization for Logs
   - https://cwe.mitre.org/data/definitions/117.html
   - https://owasp.org/www-community/attacks/Log_Injection
   - https://docs.veracode.com/r/review_cleansers?tocId=nYnZqAenFFZmB75MQrZwuA
- [x] [code-1 link](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/http/src/main/java/org/ballerinalang/net/http/HTTPServicesRegistry.java#L104)
- [x] [code-2 link](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/http/src/main/java/org/ballerinalang/net/http/HTTPServicesRegistry.java#L211)
- [x] [code-3 link](https://github.com/ballerina-platform/ballerina-lang/blob/ballerina-1.2.x/stdlib/http/src/main/java/org/ballerinalang/net/http/HttpUtil.java#L427)
