### ISSUE TITLE
Enable tests [update2]

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#5344]
**Description:**

- [x] https://github.com/ballerina-platform/openapi-tools/issues/1033 (Client test.bal generation tests)
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/2966 (Enum test Ballerina to OpenAPI)
- [x] https://github.com/ballerina-platform/openapi-tools/issues/1013 (Reference resolve tests Balleirna to OpenAPI)
- [x] https://github.com/ballerina-platform/ballerina-standard-library/issues/3123 (Tuple type support Ballerina to OpenAPI)

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
