### ISSUE TITLE
Introduce the OpenAPI annotation for mapping values to OAS info section meta deta

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-standard-library#5533]
**Description:**
OpenAPI has below mandatory field need to fill with values, currently, the values suggested to fill with default
```
info:
  version: 1.0.0
  title: Service Name 
```
Hope to introduce the OpenAPI annotation to override the default values as user wants,
```ballerina
openapi:ServiceInfo {
    title?: “Service Title”,
    version?: “1.0.1”
}
```
 **Action items**
-  Update the contract generation behaviour when the following attributes are provided in the annotation
- [x] **Path, Title, version** -> Generate a new contract by replacing the existing title and version in the given contract
- [x] **Path, Title** ->Generate a new contract by replacing the existing title in the given contract
- [x] **Path, Version** ->Generate a new contract by replacing the existing version in the given contract
- [x] **Title, Version** ->Generate with provided title and version
- [x] **Path** ->Skip contract generation
- [x] **Title** ->Generate with provided title and package version
- [x] **Version**->Generate with provided version and base path as the title
