### ISSUE TITLE
Map multiline descriptions in open-api definition to doc comments on ballerina

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-standard-library#5542]
**Description:**
Often, the descriptions in open-api definitions are multi-line. 
Eg: 
```
description: >+
        Use this API to register up to 30 registrants at once for a
        scheduled webinar that requires
        [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration).
        <br>


        **Prerequisites:**<br>

        * The webinar host must be a Licensed user.

        * The webinar should be of type `5`, i.e., it should be a scheduled webinar. Other types of webinars are not supported by this API.<br><br>

        **Scope:** `webinar:write`, `webinar:write:admin`<br>

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>
```
Currently we are only getting the first line of the description as the doc comment

#### Sub-tasks
At the completion of this task, multi line doc comments in the following sections of a ballerina connector should be generated successfully

- [x] Client class description
- [x] Client init description
- [x] Remote function description
- [x] Remote function parameter description
- [x] Remote function return description
- [x] Record description
- [x] Record field description

**Suggested Labels:**
> client
> improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
