### ISSUE TITLE
Implement new HTTP service design

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#576]
#### Purpose
> [Design doc](https://docs.google.com/document/d/1d4ZdVZw1PmhhoHkjevIM5BzRaeuIot0jUrmZQQZl_SY/edit#heading=h.3vwqe27ywmv)
> [Spec doc](https://docs.google.com/document/d/1qlSMnN8dUnb01DUKCLWzDz1V80ygIkhthoqMKxyGEkk/edit?usp=sharing)

#### Task
- [x] [Introduce query params to the resource signature](https://github.com/ballerina-platform/ballerina-standard-library/issues/593)
- [x] [Introduce @http:Payload annotation](https://github.com/ballerina-platform/ballerina-standard-library/issues/594)
- [x] [Path param and Wildcard feature](https://github.com/ballerina-platform/ballerina-standard-library/issues/595)
- [x] [Introduce HTTP verb to the resource function](https://github.com/ballerina-platform/ballerina-standard-library/issues/596)
- [x] [Add return types, status code objects and response record](https://github.com/ballerina-platform/ballerina-standard-library/issues/597)
- [x] [Listener and Client init method return errors](https://github.com/ballerina-platform/ballerina-standard-library/issues/817)
- [x] [Improve getHeader() API to return error](https://github.com/ballerina-platform/ballerina-standard-library/issues/336)
- [x] [Change request limit config location in listener configs](https://github.com/ballerina-platform/ballerina-standard-library/issues/834)
- [x] [Introduce getByteStream/setByteStream functions](https://github.com/ballerina-platform/ballerina-standard-library/issues/863)

#### API removal
- [x] [Remove ok(), accept(),.. etc caller remote methods](https://github.com/ballerina-platform/ballerina-standard-library/issues/855)
- [x] [Remove channel usages - getByteChannel(), ... etc
](https://github.com/ballerina-platform/ballerina-standard-library/issues/856)
#### New features
- [x] [Introduce @http:Header annotation](https://github.com/ballerina-platform/ballerina-standard-library/issues/689)
- [x]  Compiler validation

#### Client
- [x] Remove the casting 
- [x] Fix errors with distinct hierarchies 
- [ ] [Introduce default client](https://github.com/ballerina-platform/ballerina-standard-library/issues/969) 
- [x] Add header map for all the actions 
- [x] Finalize the types that can be directly sent by the client

#### Post Beta (GA)
- [x] [Common error handling resource/function](https://github.com/ballerina-platform/ballerina-standard-library/issues/693)
- [x] [Introduce http:CallerInfo annotation validation
](https://github.com/ballerina-platform/ballerina-standard-library/issues/744)
- [ ] [Introduce HTTP session](https://github.com/ballerina-platform/ballerina-standard-library/issues/691)
- [x] [Introduce HTTP Filters](https://github.com/ballerina-platform/ballerina-standard-library/issues/692)
- [ ] [Add 417,406 validation to @http:Payload annotation](https://github.com/ballerina-platform/ballerina-standard-library/issues/897)

**Comment by chamil321** [comment]
Closing the issue as the most of the priority issue are implemented and remaining issue are tracked in individual issues
