### ISSUE TITLE
Implement new Websocket service 

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-standard-library#577]
Spec: https://docs.google.com/document/d/112iUKhqqsC1-Z62myUS72RNIz1n7zybLJiJfsEQhdMw/edit?usp=sharing

**Moving to a new repository**
- [x] [Move WebSocket code to a new repository](https://github.com/ballerina-platform/ballerina-standard-library/issues/687). 
- - [x] Move the client code
- - [x] Move the server code

**Listener and service**
- [x] Implement the new service type design
- - [x] [Add a new listener for WebSocket](https://github.com/ballerina-platform/ballerina-standard-library/issues/688)
- - [x] Create websocket listener using the http:Listener (Need to discuss)
- - [x] [Server side should include a new service for handling upgrade requests](https://github.com/ballerina-platform/ballerina-standard-library/issues/690)
- - [x] Remove caller from the remote functions. (Not finalized)
- - [x] Query param, path param support for WebSocket upgrade service.
- - [x] Custom headers
- - [x] [Change Listener method to return errors](https://github.com/ballerina-platform/ballerina-standard-library/issues/819)
- - [x] [Add Auth support](https://github.com/ballerina-platform/ballerina-standard-library/issues/820)
- - [x] Migrate BBEs

***Post Alpha***
- - [x] [Compiler plugin validation for service](https://github.com/ballerina-platform/ballerina-standard-library/issues/778)
- - [x] Chunk Messages - https://github.com/ballerina-platform/ballerina-standard-library/issues/828
- - [x] Revisit errors - https://github.com/ballerina-platform/ballerina-standard-library/issues/923

**Sync client (Primary)**
- [x] [Finalize the new client design](https://docs.google.com/document/d/112iUKhqqsC1-Z62myUS72RNIz1n7zybLJiJfsEQhdMw/edit?usp=sharing) - 
- [x] Initial implementation
- [x] Add BBEs and documentation

 ***Post SL GA***
- [ ] ~Failover implementation~
- [x] Retry implementation
- [x] [Cookie support](https://github.com/ballerina-platform/ballerina-standard-library/issues/978)
- [x] [Add Auth support](https://github.com/ballerina-platform/ballerina-standard-library/issues/820)
- [x] [Compiler plugin validation](https://github.com/ballerina-platform/ballerina-standard-library/issues/778)

**Async client (Secondary)**
- Spec: https://docs.google.com/document/d/112iUKhqqsC1-Z62myUS72RNIz1n7zybLJiJfsEQhdMw/edit?usp=sharing
Need to align websocket async client according to the new design mentioned in the spec.
- [x] Take the callback service in client init.
- [x] Rename `pushText` and `pushBinary` to `writeTextMessage` and `writeBinaryMessage`
- [x] Rename `onBinary` and `onText` to `onBinaryMessage` and `onTextMessage`
- [x] Remove readyOnConnect API
- [x] [Change Client init method to return errors](https://github.com/ballerina-platform/ballerina-standard-library/issues/819)
- [x] Update BBEs

***Post SW GA***
- [ ] ~Failover implementation~
- [x] Retry implementation
- [x] Cookie support
- [x] [Add Auth support](https://github.com/ballerina-platform/ballerina-standard-library/issues/820)
- [x] Compiler plugin validation

**Comment by Bhashinee** [comment]
Closing the issue as the service implementation is done.
