### ISSUE TITLE
Security Implementation for Swan Lake

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-standard-library#584]
## Important Links
- Dashboard: https://ldclakmal.me/ballerina-security
- `Area/Security` Issues: https://ldclakmal.me/ballerina-security/issues/

### Proposed Designs:
- Design of Ballerina Authentication & Authorization Framework - Swan Lake Version
https://docs.google.com/document/d/1dGw5uUP6kqZNTwMfQ_Ik-k0HTMKhX70XpEA3tys9_kk/edit?usp=sharing
- Re-Design of Ballerina SecureSocket API - Swan Lake Version
https://docs.google.com/document/d/1Y2kLTOw9-sRK1vSEzw5NYdWSA4nwVCvPf3wrbwNDA4s/edit?usp=sharing
- [Review] Ballerina Security APIs of StdLib PCMs https://docs.google.com/document/d/16r_gjBi7SIqVffKVLtKGBevHQRxp7Fnoo9ELyIWV1BM/edit?usp=sharing
---

# Swan Lake Alpha

#### ballerina/auth
- [x] Update and refactor ballerina/auth module APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/715

#### ballerina/jwt
- [x] Update and refactor ballerina/jwt module APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/716

#### ballerina/oauth2
- [x] Update and refactor ballerina/oauth2 module APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/717
- [x] Add support to add optional parameters in OAuth2 introspection request https://github.com/ballerina-platform/ballerina-standard-library/issues/23
- [x] Add support to read custom fields of OAuth2 introspection response https://github.com/ballerina-platform/ballerina-standard-library/issues/16
- [x] oauth2:OutboundOAuth2Provider is not renewing access token when downstream web API returns 403 https://github.com/ballerina-platform/ballerina-standard-library/issues/17

#### ballerina/ldap
- [x] Remove ballerina/ldap module by moving implementation to ballerina/auth module https://github.com/ballerina-platform/ballerina-standard-library/issues/718

#### ballerina/http
- [x] Implement imperative auth design for ballerina/http module https://github.com/ballerina-platform/ballerina-standard-library/issues/752
- [x] Implement declarative auth design for ballerina/http module https://github.com/ballerina-platform/ballerina-standard-library/issues/813
- [x] Align stdlib annotations with spec https://github.com/ballerina-platform/ballerina-standard-library/issues/74
- [x] Improve Ballerina authn & authz configurations https://github.com/ballerina-platform/ballerina-standard-library/issues/63
- [x] Add support to provide a custom claim name as authorization claim field https://github.com/ballerina-platform/ballerina-standard-library/issues/553

#### Common
- [x] Revisit security related BBEs with all the supported features https://github.com/ballerina-platform/ballerina-standard-library/issues/60

---

# Swan Lake Beta

#### Common
- [x] Improve error messages and log messages of security modules https://github.com/ballerina-platform/ballerina-standard-library/issues/1242

#### ballerina/http
- [x] Error while trying to authorize the request when `scopes` filed is not configured https://github.com/ballerina-platform/ballerina-standard-library/issues/972
- [x] Append auth provider error message to `http:Unauthorized` and `http:Forbidden` response types https://github.com/ballerina-platform/ballerina-standard-library/issues/974
- [x] Replace ballerina/reflect API usages in ballerina/http module https://github.com/ballerina-platform/ballerina-standard-library/issues/1012
- [x] Extend listener auth handler APIs for `http:Headers` class https://github.com/ballerina-platform/ballerina-standard-library/issues/1013
- [x] Update `SecureSocket` API of HTTP https://github.com/ballerina-platform/ballerina-standard-library/issues/917

#### ballerina/auth
- [x] Enable basic auth file user store support https://github.com/ballerina-platform/ballerina-standard-library/issues/862
- [x] Update SecureSocket API of LDAP https://github.com/ballerina-platform/ballerina-standard-library/issues/1215
- [x] Remove encrypted and hashed password support https://github.com/ballerina-platform/ballerina-standard-library/issues/1214
- [x] Improve ballerina/auth test coverage https://github.com/ballerina-platform/ballerina-standard-library/issues/1011

#### ballerina/jwt
- [x] Split JWT validation API for 2 APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/1213
- [x] Replace base64 URL encode/decode APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/1212
- [x] Extend private key/public cert support for JWT signature generation/validation https://github.com/ballerina-platform/ballerina-standard-library/issues/822
- [x] Improve SSL configurations in JDK11 HTTP client used for auth modules https://github.com/ballerina-platform/ballerina-standard-library/issues/936
- [x] Add `jti` claim as a user input for JWT generation https://github.com/ballerina-platform/ballerina-standard-library/issues/1210
- [x] Improve ballerina/jwt test coverage https://github.com/ballerina-platform/ballerina-standard-library/issues/1010

#### ballerina/oauth2
- [x] JDK11 HTTP client used for OAuth2 introspection should support OAuth2 client authentication https://github.com/ballerina-platform/ballerina-standard-library/issues/935
- [x] Improve SSL configurations in JDK11 HTTP client used for auth modules https://github.com/ballerina-platform/ballerina-standard-library/issues/936
- [x] Improve the logic of extracting refresh_token from the authorization endpoint response https://github.com/ballerina-platform/ballerina-standard-library/issues/1206
- [x] Improve ballerina/oauth2 test coverage https://github.com/ballerina-platform/ballerina-standard-library/issues/1009

#### ballerina/ldap
- [x] Move ballerina/ldap module to [ballerina-attic](https://github.com/ballerina-attic)

#### ballerina/crypto
- [x] Add support for reading public/private keys from PEM files https://github.com/ballerina-platform/ballerina-standard-library/issues/67
- [x] Improve private key decoding for PKCS8 format https://github.com/ballerina-platform/ballerina-standard-library/issues/1208
- [x] Update and refactor ballerina/crypto module APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/908
- [x] Improve ballerina/crypto test coverage https://github.com/ballerina-platform/ballerina-standard-library/issues/1297

#### ballerina/encoding
- [x] Update and refactor ballerina/encoding module APIs https://github.com/ballerina-platform/ballerina-standard-library/issues/907

#### ballerina/websocket
- [x] Add auth support for WebSocket clients https://github.com/ballerina-platform/ballerina-standard-library/issues/820

#### ballerina/graphql
- [x] Implement declarative auth design for GraphQL module https://github.com/ballerina-platform/ballerina-standard-library/issues/1336

---

# Swan Lake GA

#### Common
- [x] Revisit security related APIs across all StdLibs https://github.com/ballerina-platform/ballerina-standard-library/issues/1066

#### ballerina/websocket
- [x] Implement declarative auth design for server side https://github.com/ballerina-platform/ballerina-standard-library/issues/1405
- [x] Need to improve return of WebSocket server side auth errors https://github.com/ballerina-platform/ballerina-standard-library/issues/1230

#### ballerina/ftp
- [x] Implement Security for FTP https://github.com/ballerina-platform/ballerina-standard-library/issues/1438

**Comment by ldclakmal** [comment]
### ballerina/auth
- [ ] Align stdlib annotations with spec https://github.com/ballerina-platform/ballerina-standard-library/issues/74
- [ ] Improve Ballerina authn & authz configurations https://github.com/ballerina-platform/ballerina-standard-library/issues/63
- [ ] Basic Auth inbound authentication using users defined in code https://github.com/ballerina-platform/ballerina-standard-library/issues/12
- [ ] Add support to provide a custom claim name as authorization claim field https://github.com/ballerina-platform/ballerina-standard-library/issues/553

### ballerina/jwt


### ballerina/oauth2
- [ ] Decouple and update OAuth2 APIs according to Grant Types https://github.com/ballerina-platform/ballerina-standard-library/issues/676
- [ ] Add support to add optional parameters in OAuth2 introspection request https://github.com/ballerina-platform/ballerina-standard-library/issues/23
- [ ] Add support to read custom fields of OAuth2 introspection response https://github.com/ballerina-platform/ballerina-standard-library/issues/16
- [ ] oauth2:OutboundOAuth2Provider is not renewing access token when downstream web API returns 403 https://github.com/ballerina-platform/ballerina-standard-library/issues/17

### ballerina/ldap

**Comment by ldclakmal** [comment]
The mandatory issues for SwanLake Beta was done. The remaining issues are need to be prioritized with module owners. Starting with SwanLake Beta, this tracking effort is continued with the custom Dashboard [1]. Hence closing the issue.

[1] https://ldclakmal.me/ballerina-security/issues/
