### ISSUE TITLE
New service design changes and other features in Email module

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#801]
#### Purpose
> [Design doc](https://docs.google.com/document/d/1medOxpHe1durRvO_27Kxv5qeYQlTBqeB6czyfMti4pw/edit?usp=sharing)

#### Task
- [x] [Add optional parameter based API](https://github.com/ballerina-platform/ballerina-standard-library/issues/802)
- [x] [Add optional `htmlBody` type `email:Message`](https://github.com/ballerina-platform/ballerina-standard-library/issues/777)
- [x] [Add union types for `string` typed union types for `to`, `cc`, `bcc` and `replyto` fields of the `email:Message`](https://github.com/ballerina-platform/ballerina-standard-library/issues/776)
- [x] [Simplified Email Attachments](https://github.com/ballerina-platform/ballerina-standard-library/issues/685)
- [x] [Self-signed Certificate Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/684)
- [x] [StartTLS and SSL Configuration and Implementation](https://github.com/ballerina-platform/ballerina-standard-library/issues/683)
- [x] [Return Error Union Type with Client/Listener Initialization](https://github.com/ballerina-platform/ballerina-standard-library/issues/682)
- [x] Complier Extension for Validation
- [ ] Distinct sub-error types

**Comment by Maninda** [comment]
Closing this issue as the remaining task has an issue already: https://github.com/ballerina-platform/ballerina-standard-library/issues/928
