### ISSUE TITLE
Implement Proposed design of RabbitMQ for Ballerina Swan Lake

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#804]
## Purpose
Implement proposed design for RabbitMQ client APIs and Services for Ballerina Swan Lake
**Client API design:** https://docs.google.com/document/d/1O_RRExICxYxzBoOpmxayqBRuf_UGzF-4BxVuQ_M7MI8/edit?usp=sharing
**Service changes:** https://docs.google.com/document/d/1AS1BD0qPdP1E870GKowwvcsoFb8ij9aS78X3y6Zop-Y/edit?usp=sharing

## Sub Tasks
- [x] Add support to pull messages (synchronous consuming)
- [x] Add support for creating a queue with auto-generated names
- [x] Implement support for security configurations
- [x] Add support for onRequest() remote function
- [x] Add support for reading the queue name from the service name
- [x] Return errors in client and listener init

## Low Priority
- [ ] Add support for creating connections with the URI
- [ ] Add error types
- [ ] [Add tests for transactions](https://github.com/ballerina-platform/ballerina-standard-library/issues/606) 
- [ ] [Increase test coverage](https://github.com/ballerina-platform/ballerina-standard-library/issues/234) 
- [ ] Add support for quorum queues

## Remarks
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/662
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/583
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/798
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/231

## Post Swan Lake
- [ ] [Add data binding support for RabbitMQ services](https://github.com/ballerina-platform/ballerina-standard-library/issues/796)
