### ISSUE TITLE
Implement Proposed design of Kafka for Ballerina Swan Lake

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-standard-library#807]
## Purpose
Implement proposed design for Kafka client APIs and Services for Ballerina Swan Lake
**Client API design:** https://docs.google.com/document/d/1O_RRExICxYxzBoOpmxayqBRuf_UGzF-4BxVuQ_M7MI8/edit?usp=sharing
**Service changes:** https://docs.google.com/document/d/1AS1BD0qPdP1E870GKowwvcsoFb8ij9aS78X3y6Zop-Y/edit?usp=sharing

## Sub Tasks
- [x] Implement support for security configurations and secure connections
- [x] Client API changes
- [x] Service changes
- [x] Return error in client and listener init functions
- [x] [Bump Kafka client version](https://github.com/ballerina-platform/ballerina-standard-library/issues/255)

## Low Priority
- [ ] [Add tests for transactions](https://github.com/ballerina-platform/ballerina-standard-library/issues/606)
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/247
- [ ] [Add error types](https://github.com/ballerina-platform/ballerina-standard-library/issues/252)

## Remarks
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/800
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/663
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/583
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/245
