### ISSUE TITLE
New service design changes and other features in TCP module

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-standard-library#810]
#### Purpose
> [Design doc](https://docs.google.com/document/d/1uHH_bi550n17Oj_ubYM4Xh0TjK-bIFHPfZKq7_X7h88/edit?usp=sharing)

#### Task
- [x] [Service Type Changes to Socket Module](https://github.com/ballerina-platform/ballerina-standard-library/issues/700)
- [x] [Introduce `readBytes` and `writeBytes` to Socket Client](https://github.com/ballerina-platform/ballerina-standard-library/issues/698)
- [x] [Introduce Transport Security to TCP Sockets](https://github.com/ballerina-platform/ballerina-standard-library/issues/711)
- [x] Complier plugin to validate service types

**Comment by Bhashinee** [comment]
Closing the issue as this is done.
