### ISSUE TITLE
Implement New GraphQL Service Design

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#825]
### Docs

* [Design Doc](https://docs.google.com/document/d/1h8GITWRay_WxN22XZ9XjnWncweucXLGa06ERZ1qzIfM/edit#heading=h.ugr2w88qjs8u)

### Tasks
- [x] [GraphQL Parser with Visitor Support](https://github.com/ballerina-platform/ballerina-standard-library/issues/598)
- [x] [Parse documents with parameters](https://github.com/ballerina-platform/ballerina-standard-library/issues/220)
- [x] [Handle resource functions without input parameters ](https://github.com/ballerina-platform/ballerina-standard-library/issues/641)
- [x] [Handle resource functions with input parameters](https://github.com/ballerina-platform/ballerina-standard-library/issues/642)
- [x] [Handle resource functions returning record values](https://github.com/ballerina-platform/ballerina-standard-library/issues/644)
- [x] [Handle resource functions returning service objects](https://github.com/ballerina-platform/ballerina-standard-library/issues/643)
- [x] [Handle resource functions returning arrays](https://github.com/ballerina-platform/ballerina-standard-library/issues/646)
- [x] [Generate a schema for an attached service](https://github.com/ballerina-platform/ballerina-standard-library/issues/696)
- [x] [Support resource functions returning union with errors](https://github.com/ballerina-platform/ballerina-standard-library/issues/762)
- [x] [Support introspection queries](https://github.com/ballerina-platform/ballerina-standard-library/issues/697)
- [x] [Handle hierarchical resource paths](https://github.com/ballerina-platform/ballerina-standard-library/issues/779)
- [x] [Support `map` type](https://github.com/ballerina-platform/ballerina-standard-library/issues/999)
- [x] [Support resource functions returning `table` values](https://github.com/ballerina-platform/ballerina-standard-library/issues/648)
- [x] [Support resource functions returning `enum` values](https://github.com/ballerina-platform/ballerina-standard-library/issues/1000)
- [x] [Support union types in GraphQL](https://github.com/ballerina-platform/ballerina-standard-library/issues/1001)
- [x] [Support Syntactic Sugar in GraphQL documents](https://github.com/ballerina-platform/ballerina-standard-library/issues/1002)

### Features
- [x] [Implement GraphQL Listener](https://github.com/ballerina-platform/ballerina-standard-library/issues/223)
- [x] [Implement GraphQL Engine](https://github.com/ballerina-platform/ballerina-standard-library/issues/824)
- [x] [Implement GraphQL Parser](https://github.com/ballerina-platform/ballerina-standard-library/issues/221)
- [x] [Implement a simple GraphQL client for handle GraphQL requests](https://github.com/ballerina-platform/ballerina-standard-library/issues/735)

### Post Alpha
- [x] [Compiler Validation](https://github.com/ballerina-platform/ballerina-standard-library/issues/1091)
- [x] [Securing a GraphQL service](https://github.com/ballerina-platform/ballerina-standard-library/issues/710)

**Comment by ThisaruGuruge** [comment]
Closing as all the steps are now completed.
