### ISSUE TITLE
Implement Ballerina Serdes Module Design

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-standard-library#924]
Design and implement the Serdes module for Ballerina Standard Library.

### Subtasks

- [ ] Complete the Native Implementation (#931)
- [ ] Implement the Proto Serializer APIs in Ballerina (#994)
- [ ] Implement the Proto Deserializer APIs in Ballerina (#995)

Assignee: @TharindaDilshan 

Initial Proposal: #780

**Comment by TharindaDilshan** [comment]
Supported Data Types

- Primitive Types (string, int, float, boolean, byte)
- Array Types
- Record Types
